# Generated by Django 5.0.6 on 2024-06-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_character_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
