# Generated by Django 5.0.6 on 2024-06-26 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_alter_character_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='user',
        ),
    ]
