# Generated by Django 5.0.6 on 2024-06-26 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=5)),
                ('water_supply', models.FloatField(default=100.0)),
                ('food_supply', models.FloatField(default=100.0)),
            ],
        ),
        migrations.CreateModel(
            name='TrailerCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trailer.trailer')),
            ],
            options={
                'unique_together': {('trailer', 'character')},
            },
        ),
    ]
