# Generated by Django 5.0.6 on 2024-07-02 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.item')),
                ('health_value', models.IntegerField(default=5)),
                ('expiration_date', models.DateField(blank=True, null=True)),
            ],
            bases=('items.item',),
        ),
        migrations.RemoveField(
            model_name='item',
            name='weight',
        ),
    ]
