# Generated by Django 5.0.6 on 2024-07-02 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_food_remove_item_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apple',
            fields=[
                ('food_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.food')),
            ],
            bases=('items.food',),
        ),
        migrations.CreateModel(
            name='Bread',
            fields=[
                ('food_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.food')),
            ],
            bases=('items.food',),
        ),
        migrations.AddField(
            model_name='item',
            name='value',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='food',
            name='health_value',
            field=models.IntegerField(),
        ),
    ]
