# Generated by Django 5.0.6 on 2024-07-02 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('forest', 'Forest'), ('desert', 'Desert'), ('plain', 'plain'), ('mountain', 'Mountain')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x_coordinate', models.IntegerField()),
                ('y_coordinate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MainMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main_Map', max_length=70)),
                ('width', models.IntegerField(default=10)),
                ('height', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cave',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='locations.location')),
                ('depth', models.IntegerField()),
            ],
            bases=('locations.location',),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='locations.location')),
                ('population', models.PositiveIntegerField()),
            ],
            bases=('locations.location',),
        ),
        migrations.CreateModel(
            name='Forest',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='locations.location')),
            ],
            bases=('locations.location',),
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('x_coordinate', models.IntegerField()),
                ('y_coordinate', models.IntegerField()),
                ('width', models.PositiveIntegerField(default=4)),
                ('height', models.PositiveIntegerField(default=4)),
                ('main_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='locations.mainmap')),
            ],
            options={
                'unique_together': {('main_map', 'x_coordinate', 'y_coordinate')},
            },
        ),
        migrations.AddField(
            model_name='location',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='locations.map'),
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.IntegerField(default=0)),
                ('y_coordinate', models.IntegerField(default=0)),
                ('box_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.boxtype')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='locations.map')),
            ],
            options={
                'unique_together': {('map', 'x_coordinate', 'y_coordinate')},
            },
        ),
    ]
