# Generated by Django 5.0.6 on 2024-07-02 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=5)),
                ('water_supply', models.FloatField(default=100.0)),
                ('food_supply', models.FloatField(default=100.0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trailers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrailerCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trailers.trailer')),
            ],
            options={
                'unique_together': {('trailer', 'character')},
            },
        ),
        migrations.AddField(
            model_name='trailer',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='trailers', through='trailers.TrailerCharacter', to='characters.character'),
        ),
    ]
